// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqQ0szMTm7RvVPDJRtqpyRYvikkUhTjsM',
    appId: '1:874343811496:web:df3dbed965db5f13c6359d',
    messagingSenderId: '874343811496',
    projectId: 'lockalista',
    authDomain: 'lockalista.firebaseapp.com',
    storageBucket: 'lockalista.firebasestorage.app',
    measurementId: 'G-XFBRQYR0EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwikQf1uigBcnZsbcNHhf18g_5Lg9Be44',
    appId: '1:874343811496:android:5514c44c3317652bc6359d',
    messagingSenderId: '874343811496',
    projectId: 'lockalista',
    storageBucket: 'lockalista.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFeJVP39dxMsMNkDK-Ap6asXOLZ2yMBec',
    appId: '1:874343811496:ios:28d3e736f4ad2195c6359d',
    messagingSenderId: '874343811496',
    projectId: 'lockalista',
    storageBucket: 'lockalista.firebasestorage.app',
    androidClientId: '874343811496-8ds5utrtk3bb208bkan8vnu2airh1s5i.apps.googleusercontent.com',
    iosClientId: '874343811496-sn993r9eer2bc184akf4q0bd0sqar70i.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockalista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFeJVP39dxMsMNkDK-Ap6asXOLZ2yMBec',
    appId: '1:874343811496:ios:28d3e736f4ad2195c6359d',
    messagingSenderId: '874343811496',
    projectId: 'lockalista',
    storageBucket: 'lockalista.firebasestorage.app',
    androidClientId: '874343811496-8ds5utrtk3bb208bkan8vnu2airh1s5i.apps.googleusercontent.com',
    iosClientId: '874343811496-sn993r9eer2bc184akf4q0bd0sqar70i.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockalista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqQ0szMTm7RvVPDJRtqpyRYvikkUhTjsM',
    appId: '1:874343811496:web:f2f785aec31121f4c6359d',
    messagingSenderId: '874343811496',
    projectId: 'lockalista',
    authDomain: 'lockalista.firebaseapp.com',
    storageBucket: 'lockalista.firebasestorage.app',
    measurementId: 'G-7248NWP39J',
  );
}
